"use strict";
console.log("Hello World from Typescript, compiler is working");
let a = 5;
console.log(a);
let b = 10;
console.log(b);
let c = 1;
c += b;
console.log("c+b =", c);
c -= a;
console.log("c-a=", c);
